[build-system]
requires = ["setuptools >= 65.0"]
build-backend = "setuptools.build_meta"

[project]
name = "distracted"
version = "0.0.1"
requires-python = ">3.10.0"

[tool.setuptools.packages.find]
where = ["src"]